
IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'PRC_PRODUTO_EXCLUIR')
	DROP PROCEDURE PRC_PRODUTO_EXCLUIR;
GO

CREATE PROCEDURE PRC_PRODUTO_EXCLUIR
(
	@ID_PRODUTO INT
)
AS
BEGIN
	UPDATE [dbo].[TB_PRODUTO] SET 
		ATIVO = 0
	WHERE
		ID_PRODUTO = @ID_PRODUTO
END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'PRC_PRODUTO_ALTERAR')
	DROP PROCEDURE PRC_PRODUTO_ALTERAR;
GO

CREATE PROCEDURE PRC_PRODUTO_ALTERAR
(
	@ID_PRODUTO INT,
	@NOME VARCHAR(50), 
	@ESTOQUE INTEGER, 
	@URL VARCHAR(200), 
	@VALOR DECIMAL(10,2), 
	@DESCRICAO VARCHAR(3000) = NULL
)
AS
BEGIN
	UPDATE [dbo].[TB_PRODUTO] SET 
		NOME = @NOME,
		ESTOQUE = ESTOQUE,
		[URL] = @URL,
		VALOR = @VALOR,
		DESCRICAO = @DESCRICAO
	WHERE
		ID_PRODUTO = @ID_PRODUTO
END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'PRC_PRODUTO_CONSULTAR')
	DROP PROCEDURE PRC_PRODUTO_CONSULTAR;
GO

CREATE PROCEDURE PRC_PRODUTO_CONSULTAR
(
	@ID_PRODUTO INT = NULL,
	@NOME VARCHAR(50) = NULL
)
AS
BEGIN

	SELECT ID_PRODUTO, DISPONIVEIS, ESTOQUE, NOME, DESCRICAO, [URL], VALOR  FROM VW_PRODUTOS_DISPONIVEIS
	WHERE (NOME LIKE '%' + ISNULL(@NOME, NOME) + '%' OR DESCRICAO LIKE '%' + ISNULL(@NOME, DESCRICAO) + '%') 
	AND ID_PRODUTO = ISNULL(@ID_PRODUTO, ID_PRODUTO);

END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'PRC_PRODUTO_INSERIR')
	DROP PROCEDURE PRC_PRODUTO_INSERIR;
GO

CREATE PROCEDURE PRC_PRODUTO_INSERIR
(
	@NOME VARCHAR(50), 
	@ESTOQUE INTEGER, 
	@URL VARCHAR(200), 
	@VALOR DECIMAL(10,2), 
	@DESCRICAO VARCHAR(3000) = NULL
)
AS
BEGIN
	INSERT INTO  [dbo].[TB_PRODUTO] (NOME, ESTOQUE, [URL], VALOR, DESCRICAO) VALUES (@NOME, @ESTOQUE, @URL, @VALOR, @DESCRICAO);
	SELECT @@IDENTITY;
END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'PRC_USUARIO_CONSULTAR')
	DROP PROCEDURE PRC_USUARIO_CONSULTAR;
GO

CREATE PROCEDURE PRC_USUARIO_CONSULTAR
(
    @ID_USUARIO INT = null,
	@NOME VARCHAR(50) = NULL,
	@EMAIL VARCHAR(50) = NULL
)
AS
BEGIN

	SELECT ID_USUARIO, NOME, SENHA, EMAIL, DATA_CADASTRO, ADMINISTRA FROM TB_USUARIO 
	WHERE ATIVO = 1 AND NOME = ISNULL(@NOME, NOME) AND EMAIL = ISNULL(@EMAIL, EMAIL) AND ID_USUARIO = ISNULL(@ID_USUARIO, ID_USUARIO)

END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'PRC_USUARIO_INSERIR')
	DROP PROCEDURE PRC_USUARIO_INSERIR;
GO

CREATE PROCEDURE PRC_USUARIO_INSERIR
(
	@NOME VARCHAR(50),
	@SENHA VARCHAR(50),
	@EMAIL VARCHAR(50)
)
AS
BEGIN

	DECLARE @ADMINISTRA BIT = 0;
	
	IF (CHARINDEX('(ADM)',UPPER(@NOME)) > 0)
		SET @ADMINISTRA = 1;

	IF EXISTS (SELECT 1 FROM TB_USUARIO WHERE EMAIL =  @EMAIL AND ATIVO = 1)
		SELECT -1;
	ELSE
	BEGIN
		INSERT INTO TB_USUARIO (NOME, SENHA, EMAIL, ADMINISTRA) VALUES (@NOME, @SENHA, @EMAIL, @ADMINISTRA);
		SELECT @@IDENTITY;
	END
END

GO


IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_CARRINHO_INCLUIR')
	DROP PROCEDURE PRC_CARRINHO_INCLUIR;
GO

CREATE PROCEDURE PRC_CARRINHO_INCLUIR
(
	@ID_USUARIO INT = NULL,
	@IDENTIFICADOR VARCHAR(50) = NULL,
	@QUANTIDADE INT = 0,
	@ID_PRODUTO INT = 0
)
AS 
BEGIN 

	DECLARE @ID_USUARIO_ATUAL INT;
	DECLARE @ID_CARRINHO_ATUAL INT;
	DECLARE @IDENTIFICADOR_ATUAL VARCHAR(50);

	IF EXISTS(SELECT 1 FROM [dbo].[VW_PRODUTOS_DISPONIVEIS] A WHERE A.ID_PRODUTO = @ID_PRODUTO AND (A.DISPONIVEIS-@QUANTIDADE) > 0 AND @QUANTIDADE > 0 AND @ID_PRODUTO > 0) 
	BEGIN
		IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO] A WHERE A.ID_USUARIO = @ID_USUARIO)
		BEGIN
			SELECT 
				@ID_CARRINHO_ATUAL = ID_CARRINHO,
				@IDENTIFICADOR_ATUAL = IDENTIFICADOR 
			FROM [dbo].[TB_CARRINHO] WHERE ID_USUARIO = @ID_USUARIO;

			IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO_PRODUTO] B WHERE B.ID_PRODUTO = @ID_PRODUTO AND B.ID_CARRINHO = @ID_CARRINHO_ATUAL)
				UPDATE [TB_CARRINHO_PRODUTO] SET
				QUANTIDADE = QUANTIDADE + @QUANTIDADE,
				DATA_CADASTRO = GETDATE()
				WHERE ID_PRODUTO = @ID_PRODUTO AND ID_CARRINHO = @ID_CARRINHO_ATUAL;
			ELSE
				INSERT INTO [TB_CARRINHO_PRODUTO] (ID_CARRINHO, ID_PRODUTO, QUANTIDADE) VALUES (@ID_CARRINHO_ATUAL, @ID_PRODUTO, @QUANTIDADE);
		END
		ELSE IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO] A WHERE A.IDENTIFICADOR = @IDENTIFICADOR)
		BEGIN
			SELECT
				@ID_CARRINHO_ATUAL = ID_CARRINHO,
				@IDENTIFICADOR_ATUAL = IDENTIFICADOR
			FROM [dbo].[TB_CARRINHO] WHERE IDENTIFICADOR = @IDENTIFICADOR;

			IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO_PRODUTO] B WHERE B.ID_PRODUTO = @ID_PRODUTO AND B.ID_CARRINHO = @ID_CARRINHO_ATUAL)
				UPDATE [TB_CARRINHO_PRODUTO] SET
				QUANTIDADE = QUANTIDADE + @QUANTIDADE,
				DATA_CADASTRO = GETDATE()
				WHERE ID_PRODUTO = @ID_PRODUTO AND ID_CARRINHO = @ID_CARRINHO_ATUAL;
			ELSE
				INSERT INTO [TB_CARRINHO_PRODUTO] (ID_CARRINHO, ID_PRODUTO, QUANTIDADE) VALUES (@ID_CARRINHO_ATUAL, @ID_PRODUTO, @QUANTIDADE);
		END
		ELSE
		BEGIN
			SET @IDENTIFICADOR_ATUAL = ISNULL(@IDENTIFICADOR, CONVERT(VARCHAR(50), NEWID()));
			INSERT INTO [dbo].[TB_CARRINHO] ([ID_USUARIO] ,[IDENTIFICADOR]) VALUES (@ID_USUARIO, @IDENTIFICADOR_ATUAL);
			SET @ID_CARRINHO_ATUAL = @@IDENTITY;

			INSERT INTO TB_CARRINHO_PRODUTO (ID_CARRINHO, ID_PRODUTO, QUANTIDADE) VALUES (@ID_CARRINHO_ATUAL, @ID_PRODUTO, @QUANTIDADE); 
		END
	END

	EXECUTE PRC_CARRINHO_CARREGAR @ID_USUARIO, @IDENTIFICADOR_ATUAL, @ID_CARRINHO_ATUAL;

END
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'PRC_CARRINHO_CARREGAR')
	DROP PROCEDURE PRC_CARRINHO_CARREGAR;
GO

CREATE PROCEDURE PRC_CARRINHO_CARREGAR 
(
	@ID_USUARIO INT = NULL,
	@IDENTIFICADOR VARCHAR(50) = NULL,
	@ID_CARRINHO INT = NULL
)
AS
BEGIN

	SELECT A.IDENTIFICADOR, A.ID_USUARIO, B.ID_PRODUTO, B.QUANTIDADE, C.[URL], C.NOME, C.VALOR, C.DESCRICAO FROM TB_CARRINHO A
	INNER JOIN TB_CARRINHO_PRODUTO B ON A.ID_CARRINHO = B.ID_CARRINHO
	INNER JOIN TB_PRODUTO C ON C.ID_PRODUTO = B.ID_PRODUTO
	WHERE 
	A.ID_CARRINHO = ISNULL(@ID_CARRINHO, 0) OR A.ID_USUARIO = ISNULL(@ID_USUARIO, 0) OR A.IDENTIFICADOR = ISNULL(@IDENTIFICADOR, '.');

END
