IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_PEDIDO_FINALIZAR')
	DROP PROCEDURE PRC_PEDIDO_FINALIZAR;
GO

CREATE PROCEDURE PRC_PEDIDO_FINALIZAR
(
	@ID_CARRINHO INT,
	@ID_USUARIO INT
)
AS
BEGIN

	DECLARE @ID_USUARIO_ATUAL INT
	DECLARE @ID_PEDIDO INT
	DECLARE @VALOR_TOTAL DECIMAL (10,2)

	SELECT @ID_USUARIO_ATUAL = ID_USUARIO ,
	@VALOR_TOTAL = (A.QUANTIDADE * B.VALOR) FROM TB_CARRINHO_PRODUTO A
	INNER JOIN VW_PRODUTOS_DISPONIVEIS B ON B.ID_PRODUTO = A.ID_PRODUTO 
	INNER JOIN TB_CARRINHO C ON C.ID_CARRINHO = A.ID_CARRINHO
    WHERE A.ID_CARRINHO = @ID_CARRINHO;
	

	IF ISNULL(@ID_USUARIO_ATUAL, 0) = ISNULL(@ID_USUARIO, -1)
	BEGIN 

		INSERT INTO TB_PEDIDO ([ID_USUARIO], [STATUS], [VALOR]) VALUES (@ID_USUARIO, 'EM_PROCESSAMENTO', @VALOR_TOTAL);

		SET @ID_PEDIDO = @@IDENTITY;

		PRINT @ID_PEDIDO

		INSERT INTO [dbo].[TB_PEDIDO_PRODUTO] (ID_PEDIDO, QUANTIDADE, ID_PRODUTO, VALOR)
		SELECT  @ID_PEDIDO ID_PEDIDO, A.QUANTIDADE, A.ID_PRODUTO, B.VALOR  
		FROM TB_CARRINHO_PRODUTO A 
		LEFT JOIN VW_PRODUTOS_DISPONIVEIS B ON B.ID_PRODUTO = A.ID_PRODUTO 
		WHERE ID_CARRINHO = @ID_CARRINHO;

		UPDATE TB_PRODUTO  SET  
		ESTOQUE = TB_PRODUTO.ESTOQUE - B.QUANTIDADE 
		FROM TB_CARRINHO_PRODUTO B
		WHERE TB_PRODUTO.ID_PRODUTO = B.ID_PRODUTO AND B.ID_CARRINHO = @ID_CARRINHO;

		DELETE FROM TB_CARRINHO_PRODUTO WHERE ID_CARRINHO = @ID_CARRINHO;
		DELETE FROM TB_CARRINHO WHERE ID_CARRINHO = @ID_CARRINHO;
	END
	ELSE
		RAISERROR (15600,-1,-1, '@ID_USUARIO NAO ENCONTRADO PARA OPERACAO');  

END

GO


IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_PRODUTO_EXCLUIR')
	DROP PROCEDURE PRC_PRODUTO_EXCLUIR;
GO

CREATE PROCEDURE PRC_PRODUTO_EXCLUIR
(
	@ID_PRODUTO INT
)
AS
BEGIN
	UPDATE [dbo].[TB_PRODUTO] SET 
		ATIVO = 0
	WHERE
		ID_PRODUTO = @ID_PRODUTO
END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_PRODUTO_ALTERAR')
	DROP PROCEDURE PRC_PRODUTO_ALTERAR;
GO

CREATE PROCEDURE PRC_PRODUTO_ALTERAR
(
	@ID_PRODUTO INT,
	@NOME VARCHAR(50), 
	@ESTOQUE INTEGER, 
	@URL VARCHAR(200), 
	@VALOR DECIMAL(10,2), 
	@DESCRICAO VARCHAR(3000) = NULL
)
AS
BEGIN
	UPDATE [dbo].[TB_PRODUTO] SET 
		NOME = @NOME,
		ESTOQUE = ESTOQUE,
		[URL] = @URL,
		VALOR = @VALOR,
		DESCRICAO = @DESCRICAO
	WHERE
		ID_PRODUTO = @ID_PRODUTO
END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_PRODUTO_CONSULTAR')
	DROP PROCEDURE PRC_PRODUTO_CONSULTAR;
GO

CREATE PROCEDURE PRC_PRODUTO_CONSULTAR
(
	@ID_PRODUTO INT = NULL,
	@NOME VARCHAR(50) = NULL
)
AS
BEGIN

	SELECT ID_PRODUTO, DISPONIVEIS, ESTOQUE, NOME, DESCRICAO, [URL], VALOR  FROM VW_PRODUTOS_DISPONIVEIS
	WHERE (NOME LIKE '%' + ISNULL(@NOME, NOME) + '%' OR DESCRICAO LIKE '%' + ISNULL(@NOME, DESCRICAO) + '%') 
	AND ID_PRODUTO = ISNULL(@ID_PRODUTO, ID_PRODUTO);

END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_PRODUTO_INSERIR')
	DROP PROCEDURE PRC_PRODUTO_INSERIR;
GO

CREATE PROCEDURE PRC_PRODUTO_INSERIR
(
	@NOME VARCHAR(50), 
	@ESTOQUE INTEGER, 
	@URL VARCHAR(200), 
	@VALOR DECIMAL(10,2), 
	@DESCRICAO VARCHAR(3000) = NULL
)
AS
BEGIN
	INSERT INTO  [dbo].[TB_PRODUTO] (NOME, ESTOQUE, [URL], VALOR, DESCRICAO) VALUES (@NOME, @ESTOQUE, @URL, @VALOR, @DESCRICAO);
	SELECT @@IDENTITY;
END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_USUARIO_CONSULTAR')
	DROP PROCEDURE PRC_USUARIO_CONSULTAR;
GO

CREATE PROCEDURE PRC_USUARIO_CONSULTAR
(
    @ID_USUARIO INT = null,
	@NOME VARCHAR(50) = NULL,
	@EMAIL VARCHAR(50) = NULL
)
AS
BEGIN

	SELECT ID_USUARIO, NOME, SENHA, EMAIL, DATA_CADASTRO, ADMINISTRA FROM TB_USUARIO 
	WHERE ATIVO = 1 AND NOME = ISNULL(@NOME, NOME) AND EMAIL = ISNULL(@EMAIL, EMAIL) AND ID_USUARIO = ISNULL(@ID_USUARIO, ID_USUARIO)

END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_USUARIO_INSERIR')
	DROP PROCEDURE PRC_USUARIO_INSERIR;
GO

CREATE PROCEDURE PRC_USUARIO_INSERIR
(
	@NOME VARCHAR(50),
	@SENHA VARCHAR(50),
	@EMAIL VARCHAR(50)
)
AS
BEGIN

	DECLARE @ADMINISTRA BIT = 0;
	
	IF (CHARINDEX('(ADM)',UPPER(@NOME)) > 0)
		SET @ADMINISTRA = 1;

	IF EXISTS (SELECT 1 FROM TB_USUARIO WHERE EMAIL =  @EMAIL AND ATIVO = 1)
		SELECT -1;
	ELSE
	BEGIN
		INSERT INTO TB_USUARIO (NOME, SENHA, EMAIL, ADMINISTRA) VALUES (@NOME, @SENHA, @EMAIL, @ADMINISTRA);
		SELECT @@IDENTITY;
	END
END

GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_CARRINHO_EXCLUIR')
	DROP PROCEDURE PRC_CARRINHO_EXCLUIR;
GO

CREATE PROCEDURE PRC_CARRINHO_EXCLUIR
(
	@ID_USUARIO INT = NULL,
	@IDENTIFICADOR VARCHAR(50) = NULL,
	@ID_CARRINHO INT = NULL,
	@ID_PRODUTO INT = NULL
)
AS 
BEGIN 

	DECLARE @ID_USUARIO_ATUAL    INT;
	DECLARE @ID_CARRINHO_ATUAL   INT;
	DECLARE @IDENTIFICADOR_ATUAL VARCHAR(50);

	SELECT 
		@ID_USUARIO_ATUAL    = A.ID_USUARIO, 
		@ID_CARRINHO_ATUAL   = A.ID_CARRINHO,
		@IDENTIFICADOR_ATUAL = A.IDENTIFICADOR
	FROM [dbo].[TB_CARRINHO] A WHERE 
		A.ID_CARRINHO = ISNULL(@ID_CARRINHO, A.ID_CARRINHO) 
		AND A.IDENTIFICADOR = ISNULL(@IDENTIFICADOR, A.IDENTIFICADOR) 
		AND ISNULL(A.ID_USUARIO,0) = ISNULL(@ID_USUARIO,ISNULL(A.ID_USUARIO,0));

	IF (@ID_USUARIO IS NOT NULL OR @IDENTIFICADOR IS NOT NULL OR @ID_CARRINHO IS NOT NULL) 
				AND EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO] A WHERE A.ID_CARRINHO = ISNULL(@ID_CARRINHO, A.ID_CARRINHO) AND A.IDENTIFICADOR = ISNULL(@IDENTIFICADOR, A.IDENTIFICADOR) AND ISNULL(A.ID_USUARIO,0) = ISNULL(@ID_USUARIO, ISNULL(A.ID_USUARIO,0)))
	BEGIN

		IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO_PRODUTO] A WHERE A.ID_PRODUTO = @ID_PRODUTO) AND @ID_PRODUTO IS NOT NULL
		BEGIN
			DELETE FROM TB_CARRINHO_PRODUTO WHERE ID_CARRINHO = @ID_CARRINHO AND ID_PRODUTO = @ID_PRODUTO; 
		END
		ELSE
		BEGIN
			DELETE FROM TB_CARRINHO_PRODUTO WHERE ID_CARRINHO = @ID_CARRINHO; 
			DELETE FROM TB_CARRINHO WHERE ID_CARRINHO = @ID_CARRINHO; 
		END
	END

	EXECUTE PRC_CARRINHO_CARREGAR @ID_USUARIO, @IDENTIFICADOR_ATUAL, @ID_CARRINHO_ATUAL;

END
GO


IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_CARRINHO_INCLUIR')
	DROP PROCEDURE PRC_CARRINHO_INCLUIR;
GO

CREATE PROCEDURE PRC_CARRINHO_INCLUIR
(
	@ID_USUARIO INT = NULL,
	@IDENTIFICADOR VARCHAR(50) = NULL,
	@QUANTIDADE INT = NULL,
	@ID_PRODUTO INT = NULL,
    @ID_CARRINHO INT = NULL

)
AS 
BEGIN 

	DECLARE @ID_USUARIO_ATUAL INT = @ID_USUARIO;
	DECLARE @ID_CARRINHO_ATUAL INT = @ID_CARRINHO;
	DECLARE @IDENTIFICADOR_ATUAL VARCHAR(50) = @IDENTIFICADOR;

	IF EXISTS(SELECT 1 FROM [dbo].[VW_PRODUTOS_DISPONIVEIS] A WHERE A.ID_PRODUTO = @ID_PRODUTO AND (A.DISPONIVEIS-@QUANTIDADE) >= 0 AND @QUANTIDADE > 0 AND @ID_PRODUTO > 0) 
	BEGIN
		IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO] A WHERE A.ID_USUARIO = @ID_USUARIO)
		BEGIN
			SELECT 
				@ID_CARRINHO_ATUAL = ID_CARRINHO,
				@IDENTIFICADOR_ATUAL = IDENTIFICADOR 
			FROM [dbo].[TB_CARRINHO] WHERE ID_USUARIO = @ID_USUARIO;

			IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO_PRODUTO] B WHERE B.ID_PRODUTO = @ID_PRODUTO AND B.ID_CARRINHO = @ID_CARRINHO_ATUAL)
				UPDATE [TB_CARRINHO_PRODUTO] SET
				QUANTIDADE = QUANTIDADE + @QUANTIDADE,
				DATA_CADASTRO = GETDATE()
				WHERE ID_PRODUTO = @ID_PRODUTO AND ID_CARRINHO = @ID_CARRINHO_ATUAL;
			ELSE
				INSERT INTO [TB_CARRINHO_PRODUTO] (ID_CARRINHO, ID_PRODUTO, QUANTIDADE) VALUES (@ID_CARRINHO_ATUAL, @ID_PRODUTO, @QUANTIDADE);
		END
		ELSE IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO] A WHERE A.IDENTIFICADOR = @IDENTIFICADOR OR A.ID_CARRINHO = @ID_CARRINHO)
		BEGIN
			SELECT
				@ID_CARRINHO_ATUAL = ID_CARRINHO,
				@IDENTIFICADOR_ATUAL = IDENTIFICADOR
			FROM [dbo].[TB_CARRINHO] WHERE IDENTIFICADOR = @IDENTIFICADOR OR ID_CARRINHO = @ID_CARRINHO;

			IF EXISTS(SELECT 1 FROM [dbo].[TB_CARRINHO_PRODUTO] B WHERE B.ID_PRODUTO = @ID_PRODUTO AND B.ID_CARRINHO = @ID_CARRINHO_ATUAL)
				UPDATE [TB_CARRINHO_PRODUTO] SET
				QUANTIDADE = QUANTIDADE + @QUANTIDADE,
				DATA_CADASTRO = GETDATE()
				WHERE ID_PRODUTO = @ID_PRODUTO AND ID_CARRINHO = @ID_CARRINHO_ATUAL;
			ELSE
				INSERT INTO [TB_CARRINHO_PRODUTO] (ID_CARRINHO, ID_PRODUTO, QUANTIDADE) VALUES (@ID_CARRINHO_ATUAL, @ID_PRODUTO, @QUANTIDADE);
		END
		ELSE
		BEGIN
			SET @IDENTIFICADOR_ATUAL = ISNULL(@IDENTIFICADOR, CONVERT(VARCHAR(50), NEWID()));
			INSERT INTO [dbo].[TB_CARRINHO] ([ID_USUARIO] ,[IDENTIFICADOR]) VALUES (@ID_USUARIO, @IDENTIFICADOR_ATUAL);
			SET @ID_CARRINHO_ATUAL = @@IDENTITY;

			INSERT INTO TB_CARRINHO_PRODUTO (ID_CARRINHO, ID_PRODUTO, QUANTIDADE) VALUES (@ID_CARRINHO_ATUAL, @ID_PRODUTO, @QUANTIDADE); 
		END
	END

	EXECUTE PRC_CARRINHO_CARREGAR @ID_USUARIO, @IDENTIFICADOR_ATUAL, @ID_CARRINHO_ATUAL;

END
GO

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.[NAME] = 'PRC_CARRINHO_CARREGAR')
	DROP PROCEDURE PRC_CARRINHO_CARREGAR;
GO

CREATE PROCEDURE PRC_CARRINHO_CARREGAR 
(
	@ID_USUARIO INT = NULL,
	@IDENTIFICADOR VARCHAR(50) = NULL,
	@ID_CARRINHO INT = NULL
)
AS
BEGIN

	SELECT A.IDENTIFICADOR, A.ID_CARRINHO, A.ID_USUARIO, B.ID_PRODUTO, B.QUANTIDADE, C.[URL], C.NOME, C.VALOR, C.DESCRICAO, C.ESTOQUE, C.DISPONIVEIS FROM TB_CARRINHO A
	INNER JOIN TB_CARRINHO_PRODUTO B ON A.ID_CARRINHO = B.ID_CARRINHO
	LEFT JOIN VW_PRODUTOS_DISPONIVEIS C ON C.ID_PRODUTO = B.ID_PRODUTO
	WHERE 
	A.ID_CARRINHO = ISNULL(@ID_CARRINHO, 0) OR A.ID_USUARIO = ISNULL(@ID_USUARIO, 0) OR A.IDENTIFICADOR = ISNULL(@IDENTIFICADOR, '.');

END
