

IF EXISTS (SELECT 1 FROM SYS.OBJECTS A WHERE A.NAME = 'VW_PRODUTOS_DISPONIVEIS')
	DROP VIEW VW_PRODUTOS_DISPONIVEIS;
GO

CREATE VIEW VW_PRODUTOS_DISPONIVEIS
AS 
	SELECT 
		A.ID_PRODUTO,
		(A.ESTOQUE - ISNULL(B.RESERVADOS,0)) AS DISPONIVEIS,
		A.ESTOQUE,
		A.NOME,
		ISNULL(A.DESCRICAO, '') AS DESCRICAO,
		A.[URL],
		A.VALOR
	FROM 
		TB_PRODUTO A 
		LEFT JOIN ( 
			SELECT B_.ID_PRODUTO, SUM(B_.QUANTIDADE) RESERVADOS 
			FROM TB_CARRINHO A_
			INNER JOIN TB_CARRINHO_PRODUTO B_ ON A_.ID_CARRINHO = B_.ID_CARRINHO
			GROUP BY B_.ID_PRODUTO) B ON A.ID_PRODUTO = B.ID_PRODUTO
	WHERE A.ATIVO = 1;

GO

	